### ISSUE TITLE
隱瞞之事 [12]，0:09:51 ，無法隱藏

### ISSUE THREAD

**Issue by karta282036** [SODAIS69/bahaBye-kan#1]
![擷取](https://user-images.githubusercontent.com/42996962/85134275-ce915880-b26e-11ea-9f2f-53b2556fff4c.PNG)

隱瞞之事 [12]，時間軸0:09:51 ，(未看先猜 失忆)

**Comment by SODAIS69** [comment]
修好囉，感謝回報
